name: "CI"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      name: "Set up Mill"
    - name: "Run Mill"
      run: mill version

  test-legacy-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      name: "Set up Mill"
      with:
        mill-version: 0.12.3
    - name: "Run Mill"
      run: mill version

  test-alpha-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      name: "Set up Mill"
      with:
        mill-version: 1.0.0-RC2
    - name: "Run Mill"
      run: mill version
